// Datos ficticios. No son vacantes activas ni una muestra real del mercado.
const places = {
  lima: {
    region: 'latam',
    country: 'pe',
    city: 'Lima',
    workMode: 'onsite',
    location: 'Lima, Perú · presencial',
  },
  mexico: {
    region: 'latam',
    country: 'mx',
    city: 'Ciudad de México',
    workMode: 'hybrid',
    location: 'Ciudad de México, México · híbrido',
  },
  brazil: {
    region: 'latam',
    country: 'br',
    city: 'São Paulo',
    workMode: 'hybrid',
    location: 'São Paulo, Brasil · híbrido',
  },
  chile: {
    region: 'latam',
    country: 'cl',
    city: 'Santiago',
    workMode: 'onsite',
    location: 'Santiago, Chile · presencial',
  },
  colombia: {
    region: 'latam',
    country: 'co',
    city: 'Bogotá',
    workMode: 'onsite',
    location: 'Bogotá, Colombia · presencial',
  },
  remoteLatam: {
    region: 'latam',
    country: null,
    city: null,
    workMode: 'remote',
    location: 'Remoto · LATAM',
  },
  unknown: {
    region: 'unknown',
    country: null,
    city: null,
    workMode: 'unknown',
    location: 'Ubicación no especificada',
  },
}

function job(id, role, company, title, description, place) {
  return { id, role, company, title, description, ...places[place] }
}

export const demoJobs = [
  job(
    'frontend-1',
    'frontend-intern',
    'Estudio de ejemplo A',
    'Frontend Intern',
    'Apoyar interfaces con React, TypeScript, JavaScript, HTML, CSS y Git.',
    'lima',
  ),
  job(
    'frontend-2',
    'frontend-intern',
    'Producto de ejemplo B',
    'Practicante de Frontend',
    'Implementar pantallas con React, JavaScript, HTML, CSS y pruebas en Cypress.',
    'mexico',
  ),
  job(
    'frontend-3',
    'frontend-intern',
    'Equipo de ejemplo C',
    'Frontend Internship',
    'Colaborar en componentes con React, TypeScript, CSS y revisión de código con Git.',
    'remoteLatam',
  ),
  job(
    'frontend-4',
    'frontend-intern',
    'Empresa de ejemplo D',
    'Frontend Intern — primer empleo',
    'Aprender JavaScript, HTML, CSS y Git junto al equipo de producto.',
    'unknown',
  ),
  job(
    'backend-1',
    'backend-intern',
    'Estudio de ejemplo A',
    'Backend Intern',
    'Crear endpoints con Python, SQL, PostgreSQL, Docker y Git.',
    'lima',
  ),
  job(
    'backend-2',
    'backend-intern',
    'Producto de ejemplo B',
    'Practicante de Backend',
    'Apoyar APIs con Python, SQL, Docker, AWS y Git.',
    'brazil',
  ),
  job(
    'backend-3',
    'backend-intern',
    'Equipo de ejemplo C',
    'Backend Internship',
    'Probar servicios con TypeScript, PostgreSQL, Docker y CI/CD.',
    'remoteLatam',
  ),
  job(
    'backend-4',
    'backend-intern',
    'Empresa de ejemplo D',
    'Backend Intern — primer empleo',
    'Aprender APIs con Python, SQL y Git dentro de un equipo pequeño.',
    'unknown',
  ),
  job(
    'data-1',
    'data-intern',
    'Estudio de ejemplo A',
    'Data Intern',
    'Preparar datos con Python, SQL, PostgreSQL y Git.',
    'lima',
  ),
  job(
    'data-2',
    'data-intern',
    'Producto de ejemplo B',
    'Practicante de Datos',
    'Validar reportes con Python, SQL, AWS y Git.',
    'mexico',
  ),
  job(
    'data-3',
    'data-intern',
    'Equipo de ejemplo C',
    'Data Internship',
    'Explorar pipelines con Python, SQL, Docker y CI/CD.',
    'remoteLatam',
  ),
  job(
    'data-4',
    'data-intern',
    'Empresa de ejemplo D',
    'Data Intern — primer empleo',
    'Apoyar la calidad de datos con Python, SQL y Git.',
    'unknown',
  ),
  job(
    'devops-1',
    'devops-intern',
    'Estudio de ejemplo A',
    'DevOps Intern',
    'Automatizar entornos con Linux, Docker, Kubernetes, Terraform y Git.',
    'lima',
  ),
  job(
    'devops-2',
    'devops-intern',
    'Producto de ejemplo B',
    'Practicante de DevOps',
    'Apoyar despliegues con AWS, Linux, Docker, CI/CD y Git.',
    'brazil',
  ),
  job(
    'devops-3',
    'devops-intern',
    'Equipo de ejemplo C',
    'DevOps Internship',
    'Aprender Kubernetes, Linux, Terraform, Docker y CI/CD.',
    'remoteLatam',
  ),
  job(
    'devops-4',
    'devops-intern',
    'Empresa de ejemplo D',
    'DevOps Intern — primer empleo',
    'Practicar Linux, Docker, Git y automatización de tareas.',
    'unknown',
  ),
  job(
    'qa-1',
    'qa-intern',
    'Estudio de ejemplo A',
    'QA Automation Intern',
    'Escribir pruebas con Playwright, JavaScript, Git y CI/CD.',
    'lima',
  ),
  job(
    'qa-2',
    'qa-intern',
    'Producto de ejemplo B',
    'Practicante de QA',
    'Revisar historias y automatizar casos con Cypress, JavaScript y Git.',
    'chile',
  ),
  job(
    'qa-3',
    'qa-intern',
    'Equipo de ejemplo C',
    'QA Internship',
    'Probar flujos con Playwright, TypeScript, HTML, CSS y CI/CD.',
    'remoteLatam',
  ),
  job(
    'qa-4',
    'qa-intern',
    'Empresa de ejemplo D',
    'QA Intern — primer empleo',
    'Aprender pruebas manuales, JavaScript y Git con acompañamiento.',
    'unknown',
  ),
  job(
    'security-1',
    'security-intern',
    'Estudio de ejemplo A',
    'Cybersecurity Intern',
    'Apoyar revisiones con Linux, Git y fundamentos de OWASP.',
    'colombia',
  ),
  job(
    'security-2',
    'security-intern',
    'Producto de ejemplo B',
    'Practicante de Ciberseguridad',
    'Documentar hallazgos de OWASP y automatizar tareas con Python y Git.',
    'brazil',
  ),
  job(
    'security-3',
    'security-intern',
    'Equipo de ejemplo C',
    'Security Internship',
    'Revisar controles con Linux, Docker, OWASP y CI/CD.',
    'remoteLatam',
  ),
  job(
    'security-4',
    'security-intern',
    'Empresa de ejemplo D',
    'Cybersecurity Intern — primer empleo',
    'Aprender fundamentos de seguridad web, Linux y Git.',
    'unknown',
  ),
]
